FROM python:3.10-slim

WORKDIR /app

RUN pip install redis

COPY . .

# Set the environment variable to determine the role
CMD ["sh", "-c", "if [ \"$ROLE\" = \"producer\" ]; then python producer.py; else python consumer.py; fi"]