version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-producer
    depends_on:
      - redis
    environment:
      - ROLE=producer
    stdin_open: true
    tty: true

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-consumer
    depends_on:
      - redis
    environment:
      - ROLE=consumer
    stdin_open: true
    tty: true

volumes:
  redis-data: